version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
    ports:
      - '3001:3001'
    environment:
      - PORT=3001

  book-service:
    build:
      context: ./book-service
    ports:
      - '3002:3002'
    environment:
      - PORT=3002

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - AUTH_URL=http://auth-service:3001
      - BOOK_URL=http://book-service:3002
    depends_on:
      - auth-service
      - book-service
